# Generated by Django 4.2.3 on 2023-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Отзывы о фильмах', 'verbose_name_plural': 'Отзывы о фильмах'},
        ),
        migrations.AddField(
            model_name='comment',
            name='pred',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
