# Generated by Django 4.2.3 on 2023-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options_comment_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], null=True, verbose_name='Score'),
        ),
    ]
