# Generated by Django 4.2.3 on 2023-07-18 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score_LSTM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='оценка по 10'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status_LSTM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Распознавание LSTM'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Отзыв должен быть на английском языке', regex='^[a-zA-Z0-9 !?;:,.<>()@"#№$-_|&*-+/\']*$')], verbose_name='Текст отзыва'),
        ),
    ]
