# Generated by Django 4.2.3 on 2023-07-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comment_score_lstm_comment_status_lstm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score_LSTM',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status_LSTM',
        ),
    ]
