# Generated by Django 4.2.3 on 2023-07-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_remove_comment_score_lstm_remove_comment_status_lstm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='оценка по 10'),
        ),
    ]
